# Generated by Django 5.0.6 on 2024-06-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CategoryID',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subvariants',
            name='SubVariantsID',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='VaraintsID',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
