# Generated by Django 5.0.6 on 2024-06-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_categoryid_subvariants_subvariantsid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created_at',
        ),
    ]
