# Generated by Django 5.0.6 on 2024-06-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_products_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
