# Generated by Django 5.0.6 on 2024-06-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_products_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
